# Welcome to Jekyll!
# 'bundle exec jekyll serve'

# title: Ananda's 
title: Ananda Badari
author: Ananda Badari
email: badari.ananda@gmail.com

description: <img src="assets/me.jpg" style="min-width:150px;max-width:40%;border-radius:50%;"><blockquote style="font-style:normal">I am currently working on my Masters (at Georgia Tech) in Computer Science, specializing in Machine Learning. I graduated with my Bachelors in Computer Science on Dec. 2021, and my Bachelors in Mathematics on May 2022 (both also from Georgia Tech).</blockquote>
url: "https://www.anandabadari.com/"
baseurl: ""
github_username:  abadari3
permalink: /:slug.html
future: true

favicon: "me.jpg" # name+extension of favicon (which must be put on the root folder)

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-target-blank

theme_config:
  back_home_text: <img src="assets/me.jpg" style="width:50px;border-radius:50%;float:left"><br><br><br>
  date_format: " "
  appearance: "auto"
  show_description: true

sass:
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
